import img1 from './campingimg/campingimg1.webp';
import img2 from './caravanimg/caravanimg2.webp';
import img3 from './caravanimg/caravanimg3.jpg';
import img4 from './caravanimg/caravanimg4.webp';
import img5 from './caravanimg/caravanimg5.webp';
import img6 from './caravanimg/caravanimg6.webp';
import img7 from './caravanimg/caravanimg7.webp';
import img8 from './caravanimg/caravanimg8.webp';
import img9 from './caravanimg/caravanimg9.webp';
import img10 from './caravanimg/caravanimg10.webp';
import img11 from './caravanimg/caravanimg11.webp';
import img12 from './caravanimg/caravanimg12.webp';
import img13 from './caravanimg/caravanimg13.webp';
import img14 from './caravanimg/caravanimg14.webp';
import img15 from './caravanimg/caravanimg15.webp';
import img16 from './caravanimg/caravanimg16.webp';
import img17 from './caravanimg/caravanimg17.webp';
import img18 from './caravanimg/caravanimg18.webp';
import img19 from './caravanimg/caravanimg19.webp';
import img20 from './caravanimg/caravanimg20.webp';
import img21 from './caravanimg/caravanimg21.webp';
import img22 from './caravanimg/caravanimg22.webp';
import img23 from './caravanimg/caravanimg23.webp';
import img24 from './caravanimg/caravanimg24.webp';
import img25 from './caravanimg/caravanimg25.webp';

export const Caravanmockdate = [
  {
    id: 1,
    name: "르벤투스S+",
    photo: `${img1}`,
    company: "Camper Co",
    cost: "90,200,000 KRW",
    type: "포터",
    license: "2종 보통",
    people: "6인",
    date: "22년 03월",
    location: "수도권",
    rate: 4.5,
    description: "Perfect caravan for family trips with comfortable seating and amenities.",
    features: ["Air conditioning", "Satellite TV", "Outdoor awning", "Solar panel"],
    category: "Family",
    availability: true
  },
  {
    id: 2,
    name: "모터홈A",
    photo: `${img2}`,
    company: "Korea Campers",
    cost: "75,000,000 KRW",
    type: "봉고",
    license: "1종 보통",
    people: "4인",
    date: "21년 12월",
    location: "강원도",
    rate: 4.2,
    description: "Compact motorhome, ideal for couples or small families.",
    features: ["Compact kitchen", "Heating system", "Comfortable beds"],
    category: "Budget",
    availability: true
  },
  {
    id: 3,
    name: "모터홈B+",
    photo: `${img3}`,
    company: "Star Camp",
    cost: "102,000,000 KRW",
    type: "봉고",
    license: "1종 보통",
    people: "6인",
    date: "23년 01월",
    location: "부산",
    rate: 4.8,
    description: "Luxurious motorhome with modern features for a comfortable trip.",
    features: ["Satellite TV", "Air conditioning", "Spacious living area"],
    category: "Luxury",
    availability: false
  },
  {
    id: 4,
    name: "르벤투스V",
    photo: `${img4}`,
    company: "Happy Caravans",
    cost: "85,500,000 KRW",
    type: "포터",
    license: "2종 보통",
    people: "5인",
    date: "20년 11월",
    location: "서울",
    rate: 4.3,
    description: "Affordable caravan with all the basic amenities for a great adventure.",
    features: ["Outdoor shower", "Storage compartments", "LED lighting"],
    category: "Budget",
    availability: true
  },
  {
    id: 5,
    name: "모터홈S",
    photo: `${img5}`,
    company: "Camper Life",
    cost: "92,300,000 KRW",
    type: "포터",
    license: "1종 대형",
    people: "7인",
    date: "22년 07월",
    location: "대구",
    rate: 4.7,
    description: "Spacious motorhome perfect for large families or groups.",
    features: ["Large windows", "Double beds", "Premium interior"],
    category: "Family",
    availability: true
  },
  {
    id: 6,
    name: "모터홈G",
    photo: `${img6}`,
    company: "Adventure Co",
    cost: "99,000,000 KRW",
    type: "봉고",
    license: "2종 보통",
    people: "6인",
    date: "21년 05월",
    location: "광주",
    rate: 4.4,
    description: "Designed for adventure seekers with off-road capabilities.",
    features: ["Off-road tires", "Solar panel", "GPS navigation"],
    category: "Adventure",
    availability: false
  },
  {
    id: 7,
    name: "르벤투스M",
    photo: `${img7}`,
    company: "Free Camp",
    cost: "80,000,000 KRW",
    type: "봉고",
    license: "1종 보통",
    people: "4인",
    date: "23년 02월",
    location: "울산",
    rate: 4.6,
    description: "Affordable and compact caravan for budget-friendly adventures.",
    features: ["Compact kitchen", "Air conditioning", "Outdoor awning"],
    category: "Budget",
    availability: true
  },
  {
    id: 8,
    name: "모터홈E",
    photo: `${img8}`,
    company: "Happy Trails",
    cost: "88,000,000 KRW",
    type: "포터",
    license: "2종 보통",
    people: "5인",
    date: "22년 04월",
    location: "수도권",
    rate: 4.1,
    description: "Comfortable motorhome for family getaways.",
    features: ["Heating system", "Large windows", "Comfortable seating"],
    category: "Family",
    availability: true
  },
  {
    id: 9,
    name: "르벤투스Z",
    photo: `${img9}`,
    company: "Comfort Camp",
    cost: "120,000,000 KRW",
    type: "봉고",
    license: "1종 대형",
    people: "8인",
    date: "21년 06월",
    location: "서울",
    rate: 4.9,
    description: "Premium caravan for luxury and comfort.",
    features: ["Satellite TV", "Luxury interior", "Spacious design"],
    category: "Luxury",
    availability: true
  },
  {
    id: 10,
    name: "모터홈X",
    photo: `${img10}`,
    company: "CampX",
    cost: "95,500,000 KRW",
    type: "포터",
    license: "1종 보통",
    people: "6인",
    date: "20년 09월",
    location: "부산",
    rate: 4.3,
    description: "Reliable caravan with all essential amenities.",
    features: ["Air conditioning", "Compact design", "Easy to drive"],
    category: "Family",
    availability: true
  },
  {
    id: 11,
    name: "르벤투스Y",
    photo: `${img11}`,
    company: "Explorer Co",
    cost: "110,300,000 KRW",
    type: "봉고",
    license: "2종 보통",
    people: "7인",
    date: "23년 03월",
    location: "대전",
    rate: 4.6,
    description: "An excellent choice for family road trips.",
    features: ["GPS navigation", "Spacious interior", "Solar panel"],
    category: "Luxury",
    availability: true
  },
  {
    id: 12,
    name: "모터홈R",
    photo: `${img12}`,
    company: "Starry Camp",
    cost: "78,000,000 KRW",
    type: "포터",
    license: "1종 보통",
    people: "5인",
    date: "22년 12월",
    location: "강원도",
    rate: 4.4,
    description: "Affordable and reliable caravan for small families.",
    features: ["Compact kitchen", "Double bed", "Storage compartments"],
    category: "Budget",
    availability: true
  },
  {
    id: 13,
    name: "르벤투스T",
    photo: `${img13}`,
    company: "Luxury Camp",
    cost: "115,000,000 KRW",
    type: "봉고",
    license: "2종 대형",
    people: "8인",
    date: "21년 11월",
    location: "서울",
    rate: 4.7,
    description: "High-end luxury caravan with premium features.",
    features: ["Luxury design", "Air conditioning", "Satellite TV"],
    category: "Luxury",
    availability: false
  },
  {
    id: 14,
    name: "모터홈F",
    photo: `${img14}`,
    company: "CampLife",
    cost: "93,500,000 KRW",
    type: "포터",
    license: "1종 보통",
    people: "6인",
    date: "22년 08월",
    location: "부산",
    rate: 4.2,
    description: "Reliable motorhome with all basic features.",
    features: ["Heating system", "Compact kitchen", "Comfortable seats"],
    category: "Family",
    availability: true
  },
  {
    id: 15,
    name: "르벤투스N",
    photo: `${img15}`,
    company: "Camping Korea",
    cost: "87,000,000 KRW",
    type: "봉고",
    license: "1종 보통",
    people: "5인",
    date: "20년 07월",
    location: "대구",
    rate: 4.0,
    description: "Affordable caravan with efficient use of space.",
    features: ["Outdoor shower", "Compact design", "Heating system"],
    category: "Budget",
    availability: true
  },
  {
    id: 16,
    name: "모터홈D",
    photo: `${img16}`,
    company: "Journey Camp",
    cost: "96,000,000 KRW",
    type: "포터",
    license: "2종 보통",
    people: "6인",
    date: "21년 04월",
    location: "광주",
    rate: 4.5,
    description: "Designed for adventurous road trips with family or friends.",
    features: ["Solar panel", "GPS navigation", "Outdoor awning"],
    category: "Adventure",
    availability: true
  },
  {
    id: 17,
    name: "르벤투스P",
    photo: `${img17}`,
    company: "K-Adventure",
    cost: "92,000,000 KRW",
    type: "봉고",
    license: "1종 대형",
    people: "7인",
    date: "23년 01월",
    location: "울산",
    rate: 4.8,
    description: "A luxurious caravan for large groups or families.",
    features: ["Double beds", "Premium interior", "Satellite TV"],
    category: "Luxury",
    availability: false
  },
  {
    id: 18,
    name: "모터홈Y",
    photo: `${img18}`,
    company: "Nomad Campers",
    cost: "89,000,000 KRW",
    type: "포터",
    license: "2종 보통",
    people: "5인",
    date: "21년 10월",
    location: "수도권",
    rate: 4.2,
    description: "Compact and reliable motorhome for short trips.",
    features: ["Heating system", "Large windows", "Comfortable seating"],
    category: "Budget",
    availability: true
  },
  {
    id: 19,
    name: "르벤투스Q",
    photo: `${img19}`,
    company: "Explore On",
    cost: "99,000,000 KRW",
    type: "봉고",
    license: "1종 보통",
    people: "6인",
    date: "22년 06월",
    location: "서울",
    rate: 4.1,
    description: "Perfect for road trips with family or small groups.",
    features: ["Air conditioning", "Compact kitchen", "Storage compartments"],
    category: "Family",
    availability: true
  },
  {
    id: 20,
    name: "모터홈Z",
    photo: `${img20}`,
    company: "Go Camp",
    cost: "108,000,000 KRW",
    type: "포터",
    license: "1종 보통",
    people: "8인",
    date: "20년 05월",
    location: "부산",
    rate: 4.5,
    description: "A reliable and spacious caravan for large groups.",
    features: ["Air conditioning", "Double beds", "Satellite TV"],
    category: "Luxury",
    availability: true
  },
  {
    id: 21,
    name: "르벤투스W",
    photo: `${img21}`,
    company: "Urban Camp",
    cost: "97,000,000 KRW",
    type: "봉고",
    license: "2종 보통",
    people: "6인",
    date: "21년 02월",
    location: "광주",
    rate: 4.3,
    description: "Reliable caravan for urban and outdoor adventures.",
    features: ["Compact kitchen", "Heating system", "Outdoor awning"],
    category: "Adventure",
    availability: true
  },
  {
    id: 22,
    name: "모터홈U",
    photo: `${img22}`,
    company: "Nature Co",
    cost: "105,000,000 KRW",
    type: "포터",
    license: "1종 보통",
    people: "7인",
    date: "22년 03월",
    location: "대전",
    rate: 4.6,
    description: "Perfect caravan for nature lovers, equipped with modern features.",
    features: ["Solar panel", "Air conditioning", "Luxury interior"],
    category: "Luxury",
    availability: true
  },
  {
    id: 23,
    name: "르벤투스E",
    photo: `${img23}`,
    company: "Camp World",
    cost: "83,000,000 KRW",
    type: "봉고",
    license: "2종 보통",
    people: "5인",
    date: "20년 08월",
    location: "강원도",
    rate: 4.1,
    description: "An affordable caravan for small families or couples.",
    features: ["Heating system", "Storage compartments", "Outdoor awning"],
    category: "Budget",
    availability: true
  },
  {
    id: 24,
    name: "모터홈N",
    photo: `${img24}`,
    company: "Dream Campers",
    cost: "99,500,000 KRW",
    type: "포터",
    license: "1종 보통",
    people: "6인",
    date: "23년 01월",
    location: "서울",
    rate: 4.4,
    description: "A reliable and well-equipped caravan for road trips.",
    features: ["Double beds", "Heating system", "Compact kitchen"],
    category: "Family",
    availability: true
  },
  {
    id: 25,
    name: "르벤투스H",
    photo: `${img25}`,
    company: "Road Camp",
    cost: "101,000,000 KRW",
    type: "봉고",
    license: "1종 대형",
    people: "8인",
    date: "22년 10월",
    location: "부산",
    rate: 4.7,
    description: "Premium caravan with luxury features for large groups.",
    features: ["Luxury interior", "Satellite TV", "Air conditioning"],
    category: "Luxury",
    availability: false
  },
];


  
